### ISSUE TITLE
Make buildable?

### ISSUE THREAD

**Issue by bufdev** [keybase/kbfs-beta#1]
Hey,

I know this isn't meant for long-term release, but there's a lot of cool code in here especially around fuse, and it would be nice to easily play with. Right now I have some hacked-up symlinks that are trying to make this work, but it's not fun.

The main problem is that the imports are for github.com/keybase/kbfs, which points to github.com/keybase/kbfs-beta/kbfs. For whatever copy script you are using, instead of copying the kbfs directory, could you copy kbfs/\* into here instead (ie the subdirectories directly to the root of this repository)? Then, at least one can just git clone this to a directory $GOPATH/src/github.com/keybase/kbfs and be fine.

The other issue is that github.com/keybase/kbfs/bserver does not exist, but it is just in a test for now.

Also, a LICENSE? :)

**Comment by strib** [comment]
Glad you're finding it useful.  Our plan is to get our real repo open-sourced in the near future (no real reason not to, we just need to find the time to clean a few things up amid all our other feature development).  As such, we're not going to be putting any effort into this repo.  It's just to facilitate homebrew and arch builds right now.  Thanks for the suggestion though.

**Comment by bufdev** [comment]
Alright. Getting some of the fuse stuff into a separate package would be really nice, btw. Let me know if I can help?

**Comment by strib** [comment]
Do you mean the `libfuse` subdirectory?  Isn't that already a separate package (from a golang perspective)?  Or do you mean a separate repo?

If you're talking about `basil.org/fuse` that's already opensourced elsewhere on bazil.org.

**Comment by bufdev** [comment]
No I meant libfuse etc, I know bazil.org/fuse well heh :)
